added error in case someone was successfully using SPIFFWORKFLOW_BACKEND_APPLICATION_ROOT w/ burnettk

diff --git a/spiffworkflow-backend/bin/boot_server_in_docker b/spiffworkflow-backend/bin/boot_server_in_docker
--- a/spiffworkflow-backend/bin/boot_server_in_docker
+++ b/spiffworkflow-backend/bin/boot_server_in_docker
@@ -47,6 +47,11 @@ fi
 
 additional_args=""
 
+app_root="${SPIFFWORKFLOW_BACKEND_APPLICATION_ROOT:-}"
+if [[ -n "$app_root" ]] && [[ "${app_root}" != "/" ]]; then
+  echo >&2 "ERROR: SPIFFWORKFLOW_BACKEND_APPLICATION_ROOT has been set. This variable has been renamed to SPIFFWORKFLOW_BACKEND_WSGI_PATH_PREFIX. Please use that instead."
+  exit 1
+fi
 path_prefix="${SPIFFWORKFLOW_BACKEND_WSGI_PATH_PREFIX:-}"
 if [[ -n "$path_prefix" ]] && [[ "${path_prefix}" != "/" ]]; then
   if ! grep -E '^/' <<<"${path_prefix}"; then
