allow running safety and macos again

diff --git a/spiffworkflow-backend/bin/run_not_nox_in_ci b/spiffworkflow-backend/bin/run_not_nox_in_ci
--- a/spiffworkflow-backend/bin/run_not_nox_in_ci
+++ b/spiffworkflow-backend/bin/run_not_nox_in_ci
@@ -8,10 +8,16 @@ trap 'error_handler ${LINENO} $?' ERR
 set -o errtrace -o errexit -o nounset -o pipefail
 
 script_dir="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
+supported_session_types=$(grep -E '^(el)?if.*\<session_type\>.*==' $0 | sed -E 's/.*== "([^"]+)".*/\1/' | tr '\n' ' ')
 
 session_type="${1:-}"
-if [[ -z "${1:-}" ]]; then
+if [[ -z "${session_type}" ]] || ! grep -qE "\<${session_type}\>" <<<"$supported_session_types"; then
+  if [[ -n "$session_type" ]]; then
+    >&2 echo "ERROR: Given session typeis not supported - ${session_type}"
+  fi
+
   >&2 echo "usage: $(basename "$0") [session_type]"
+  >&2 echo -e "\tsupported session types: ${supported_session_types}"
   exit 1
 fi
 
@@ -52,23 +58,21 @@ poetry install
 if [[ "${session_type}" == "tests" ]]; then
   setup_db_for_ci
   poetry run coverage run --parallel -m pytest
+
 elif [[ "${session_type}" == "typeguard" ]]; then
   setup_db_for_ci
   RUN_TYPEGUARD=true poetry run pytest
+
 elif [[ "${session_type}" == "mypy" ]]; then
   poetry run mypy src tests
+
 elif [[ "${session_type}" == "safety" ]]; then
   poetry run safety check --full-report
+
 elif [[ "${session_type}" == "coverage" ]]; then
-  # Check if no arguments are provided and if any .coverage.* files exist
   if ls .coverage.* 1> /dev/null 2>&1; then
-      # Combine the coverage data files
       poetry run coverage combine
   fi
-
   poetry run coverage report
   poetry run coverage xml
-else
-  >&2 echo "ERROR: Given session type - ${session_type:-} - is not supported"
-  exit 1
 fi
