force a good directory as arg 1

diff --git a/bin/run_editor b/bin/run_editor
--- a/bin/run_editor
+++ b/bin/run_editor
@@ -1,5 +1,24 @@
 #!/usr/bin/env bash
 
+#!/usr/bin/env bash
+
+function error_handler() {
+  >&2 echo "Exited with BAD EXIT CODE '${2}' in ${0} script at line: ${1}."
+  exit "$2"
+}
+trap 'error_handler ${LINENO} $?' ERR
+set -o errtrace -o errexit -o nounset -o pipefail
+
+if [[ -z "${1:-}" ]]; then
+  >&2 echo "usage: $(basename "$0") [SPIFF_EDITOR_BPMN_SPEC_DIR]"
+  exit 1
+fi
+
+if [[ ! -d "$1" ]]; then
+  >&2 echo "ERROR: the first argument must be a directory."
+  exit 1
+fi
+
 SPIFF_EDITOR_BPMN_SPEC_DIR=$1 \
 docker compose -f editor.docker-compose.yml up -d
 
