fix env var check w/ burnettk

diff --git a/spiffworkflow-frontend/bin/boot_server_in_docker b/spiffworkflow-frontend/bin/boot_server_in_docker
--- a/spiffworkflow-frontend/bin/boot_server_in_docker
+++ b/spiffworkflow-frontend/bin/boot_server_in_docker
@@ -11,7 +11,6 @@ set -o errtrace -o errexit -o nounset -o pipefail
 react_configs=$(env | grep -E "^SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_" || echo '')
 if [[ -n "$react_configs" ]]; then
   index_html_file="/usr/share/nginx/html/index.html"
-  # index_html_file="./index.html"
   if [[ ! -f "$index_html_file" ]]; then
     echo >&2 "ERROR: Could not find '${index_html_file}'. Cannot use SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG values without it."
     exit 1
@@ -23,21 +22,22 @@ if [[ -n "$react_configs" ]]; then
   fi
 
   for react_config in $react_configs; do
-    # remove surrounding single quotes if they are there and put back single quotes on the value.
-    # this is to better support json.
-    react_config_without_prefix=$(sed -E "s/^SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_([^=]*)='?(.*)'?/\1=\\'\2\\'/" <<<"${react_config}")
+    env_var=$(awk -F '=' '{print $1}' <<<"$react_config" | sed -E 's/^SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_//')
+    env_value=$(awk -F '=' '{print $2}' <<<"$react_config")
 
-    if [[ -z "$react_config_without_prefix" ]]; then
+    if [[ -z "$env_var" || -z "$env_value" ]]; then
       echo >&2 "ERROR: Could not parse react config line: '${react_config}'."
       exit 1
     fi
 
-    escaped_react_config=$(sed -E 's|/|\\/|g' <<<"${react_config_without_prefix}")
+    escaped_react_config_value=$(sed -E 's|/|\\/|g' <<<"${env_value}")
     # actually do the search and replace to add the js config to the html page
-    sed -i "s/\(window.spiffworkflowFrontendJsenv *= *{}\)/\1;window.spiffworkflowFrontendJsenv.${escaped_react_config}/" "$index_html_file"
+    sed -i "s/\(window.spiffworkflowFrontendJsenv *= *{}\)/\1;window.spiffworkflowFrontendJsenv.${env_var} = '${escaped_react_config_value}'/" "$index_html_file"
 
-    if ! grep -Eq "${react_config_without_prefix}" "$index_html_file"; then
-      echo >&2 "ERROR: Could not find '${react_config_without_prefix}' in '${index_html_file}' after search and replace. It is likely that the assumptions in boot_server_in_docker about the contents of the html page have changed. Fix the glitch in boot_server_in_docker."
+    env_value_grep_escaped=$(sed -E 's/\[/\\[/g' <<<"$env_value")
+    if ! grep -q "${env_var} = '${env_value_grep_escaped}'" "$index_html_file"; then
+      echo >&2 "ERROR: Could not find \"${env_var} = '${env_value}'\" in '${index_html_file}' after search and replace. It is likely that the assumptions in boot_server_in_docker about the contents of the html page have changed. Fix the glitch in boot_server_in_docker."
+      echo >&2 "index.html: $(cat $index_html_file)"
       exit 1
     fi
   done
