json values can be used now w/ burnettk

diff --git a/spiffworkflow-frontend/bin/boot_server_in_docker b/spiffworkflow-frontend/bin/boot_server_in_docker
--- a/spiffworkflow-frontend/bin/boot_server_in_docker
+++ b/spiffworkflow-frontend/bin/boot_server_in_docker
@@ -23,8 +23,9 @@ if [[ -n "$react_configs" ]]; then
   fi
 
   for react_config in $react_configs; do
-    echo "CONFIG: $react_config"
-    react_config_without_prefix=$(sed -E "s/^SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_([^=]*)=(.*)/\1=\\'\2\\'/" <<<"${react_config}")
+    # remove surrounding single quotes if they are there and put back single quotes on the value.
+    # this is to better support json.
+    react_config_without_prefix=$(sed -E "s/^SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_([^=]*)='?(.*)'?/\1=\\'\2\\'/" <<<"${react_config}")
 
     if [[ -z "$react_config_without_prefix" ]]; then
       echo >&2 "ERROR: Could not parse react config line: '${react_config}'."
@@ -35,10 +36,10 @@ if [[ -n "$react_configs" ]]; then
     # actually do the search and replace to add the js config to the html page
     sed -i "s/\(window.spiffworkflowFrontendJsenv *= *{}\)/\1;window.spiffworkflowFrontendJsenv.${escaped_react_config}/" "$index_html_file"
 
-    # if ! grep -Eq "${react_config_without_prefix}" "$index_html_file"; then
-    #   echo >&2 "ERROR: Could not find '${react_config_without_prefix}' in '${index_html_file}' after search and replace. It is likely that the assumptions in boot_server_in_docker about the contents of the html page have changed. Fix the glitch in boot_server_in_docker."
-    #   exit 1
-    # fi
+    if ! grep -Eq "${react_config_without_prefix}" "$index_html_file"; then
+      echo >&2 "ERROR: Could not find '${react_config_without_prefix}' in '${index_html_file}' after search and replace. It is likely that the assumptions in boot_server_in_docker about the contents of the html page have changed. Fix the glitch in boot_server_in_docker."
+      exit 1
+    fi
   done
 fi
 
