put back snyk on frontend

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -141,17 +141,18 @@ jobs:
         run: npm install --ignore-scripts --package-lock=false
         working-directory: spiffworkflow-frontend/packages/bpmn-js-spiffworkflow-react
 
-      #   # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-      #   # Use || true to not fail the pipeline
-      # - name: Snyk Code test
-      #   run: snyk code test --sarif > snyk-code.sarif || true
-      #
-      #   # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
-      # - name: Snyk Open Source monitor
-      #   run: snyk monitor --all-projects
-      #   # # uncomment to enable debug logs
-      #   # env:
-      #   #   DEBUG: "*snyk*"
+        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
+        # Use || true to not fail the pipeline
+      - name: Snyk Code test
+        run: snyk code test --sarif > snyk-code.sarif || true
+
+        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
+      - name: Snyk Open Source monitor
+        run: snyk monitor --all-projects
+        # # uncomment to enable debug logs
+        # env:
+        #   DEBUG: "*snyk*"
+
       # These are just needed for snyk
       - name: Remove node_modules
         run: rm -rf node_modules
